ma{{ if .Values.secrets }}
{{ $length := len .Values.secrets }}
{{ if gt $length 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ regexFind "[^/]+$" .Values.image }}
type: Opaque
data:
  {{ range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc}}
  {{ end }}
{{ end }}
{{ end }}
