apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.image }}
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.image_pull_secret }}
      containers:
        - name: {{ .Values.image }}
          imagePullPolicy: Never
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          {{ if .Values.env }}
          {{ $length := len .Values.env }}
          {{ if gt $length 0 }}
          env:
          {{ range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{ end }}
          {{ end }}
          {{ end }}
          {{ if .Values.secrets }}
          {{ $length := len .Values.secrets }}
          {{ if gt $length 0 }}
          envFrom:
            - secretRef:
                name: {{ regexFind "[ ^/ ]+$" .Values.image }}
          {{ end }}
          {{ end }}
      restartPolicy: Never
  backoffLimit: 0